package com.example.news_feed.persistence.tables.records;

/*
 * This file is generated by jOOQ.
 */



/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Comment on the news
     */
    public static final Comment COMMENT = Comment.COMMENT;

    /**
     * Created news
     */
    public static final Item ITEM = Item.ITEM;
}